"""
FlagRecord — Developer 1 & 2 -> Developer 3 contract.

Contains timestamp, userId, department, rawPrompt, riskCategory,
severityColor, actionTaken, policyVersion, confidenceScore,
policyMode, deploymentMode, rewrittenPrompt if applicable.
"""

from typing import Optional
from datetime import datetime
from pydantic import BaseModel, Field
from shared.enums import RiskCategory, SeverityColor, ActionType, PolicyMode, DeploymentMode, ConfidenceLevel


class FlagRecord(BaseModel):
    """Complete event record sent to the Watchtower for logging."""

    # Identifiers
    incident_id: Optional[str] = None  # Generated by Watchtower on insert
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    user_id: str
    department: str
    department_id: str

    # Prompt data
    raw_prompt: str
    rewritten_prompt: Optional[str] = None

    # Risk assessment
    risk_category: RiskCategory
    risk_score: float
    severity_color: SeverityColor
    confidence_score: ConfidenceLevel

    # Action
    action_taken: ActionType

    # Policy context
    policy_version: str
    policy_mode: PolicyMode
    deployment_mode: DeploymentMode

    # Additional context
    detected_elements_summary: list[str] = []
    rewrite_explanation: Optional[list[str]] = None
